name: mvvm
description: Flutter and MVVM

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.2.0
  cupertino_icons: ^1.0.2
  auto_route: ^3.2.2
  provider: ^6.0.2
  get_it: ^7.2.0
  realm: ^0.2.0-alpha.2
  retrofit: ^3.0.1
  logger: ^1.1.0
  flutter_secure_storage: ^5.0.2
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.1
  retrofit_generator: ^3.0.1+1
  json_serializable: ^6.1.4


flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
