name: mvvm
description: Flutter and MVVM

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.5
  auto_route: ^5.0.2
  provider: ^6.0.4
  retrofit: ^3.3.1
  logger: ^1.1.0
  floor: ^1.3.0
  flutter_secure_storage: ^6.0.0
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  auto_route_generator: ^5.0.2
  retrofit_generator: ^4.2.0
  json_serializable: ^6.5.3
  floor_generator: ^1.3.0


flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
